spring:
  config:
    activate:
      on-profile: docker
  jpa:
    show-sql: false

---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/adv_search_example}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
